name: 'sf_fire_incidents'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sf_fire_incidents:
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  # Set timezone for date parsing
  timezone: 'America/Los_Angeles'